"""
Nastaveni hry
"""
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
FPS = 60

PLAYER_WIDTH = 50           
PLAYER_HEIGHT = 30
PLAYER_SPEED = 300          # pixely za sekundu
PLAYER_LIVES = 3


BULLET_SPEED = 500          # pixely za sekundu
BULLET_WIDTH = 5
BULLET_HEIGHT = 10


ENEMY_SPEED = 120           # pixely za sekundu
ENEMY_WIDTH = 40
ENEMY_HEIGHT = 25

BOSS_SPEED = 200
BOSS_WIDTH = 120
BOSS_HEIGHT = 50
BOSS_HP = 50

MAX_WAVES = 30
